<?php

namespace Database\Seeders;

use App\Models\Area;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Area::create(['code' => 1000, 'name' => 'Producción']);
        Area::create(['code' => 1100, 'name' => 'Producción general']);
        Area::create(['code' => 1110, 'name' => 'Producción agrícola']);
        Area::create(['code' => 1111, 'name' => 'Operador de maquinaria agrícola']);
        Area::create(['code' => 1112, 'name' => 'Fruticultura']);
        Area::create(['code' => 1113, 'name' => 'Horticultura']);
        Area::create(['code' => 1114, 'name' => 'Floricultura']);
        Area::create(['code' => 1120, 'name' => 'Producción pecuaria']);
        Area::create(['code' => 1121, 'name' => 'Inseminación artificial']);
        Area::create(['code' => 1122, 'name' => 'Avicultura']);
        Area::create(['code' => 1123, 'name' => 'Cunicultura']);
        Area::create(['code' => 1124, 'name' => 'Apicultura']);
        Area::create(['code' => 1130, 'name' => 'Silvicultura']);
        Area::create(['code' => 1140, 'name' => 'Producción pesquera']);
        Area::create(['code' => 1141, 'name' => 'Acuacultura']);
        Area::create(['code' => 1210, 'name' => 'Producción minera']);
        Area::create(['code' => 1220, 'name' => 'Extracción de petróleo y gas natural']);
        Area::create(['code' => 1300, 'name' => 'Producción industrial']);
        Area::create(['code' => 1311, 'name' => 'Preparación y conservación de alimentos']);
        Area::create(['code' => 1312, 'name' => 'Elaboración de refrescos, cervezas y bebidas alcohólicas']);
        Area::create(['code' => 1313, 'name' => 'Tratamiento de agua']);
        Area::create(['code' => 1314, 'name' => 'Beneficio y fabricación de productos del tabaco']);
        Area::create(['code' => 1321, 'name' => 'Industria textil']);
        Area::create(['code' => 1322, 'name' => 'Prendas de vestir']);
        Area::create(['code' => 1323, 'name' => 'Artículos de cuero y sus productos']);
        Area::create(['code' => 1324, 'name' => 'Tapicería']);
        Area::create(['code' => 1331, 'name' => 'Operación de aserraderos']);
        Area::create(['code' => 1332, 'name' => 'Fabricación de muebles y accesorios de madera']);
        Area::create(['code' => 1333, 'name' => 'Fabricación de envases y otros artículos de madera']);
        Area::create(['code' => 1341, 'name' => 'Fabricación de pasta de celulosa, papel, cartón y sus derivados']);
        Area::create(['code' => 1342, 'name' => 'Edición']);
        Area::create(['code' => 1343, 'name' => 'Industria editorial y grafica']);
        Area::create(['code' => 1351, 'name' => 'Procesamiento de petróleo y petroquímica básica']);
        Area::create(['code' => 1352, 'name' => 'Procesamiento de químicos en general']);
        Area::create(['code' => 1353, 'name' => 'Procesamiento químico farmacéutico']);
        Area::create(['code' => 1354, 'name' => 'Fabricación y regeneración de productos de hule']);
        Area::create(['code' => 1355, 'name' => 'Fabricación de productos de plástico']);
        Area::create(['code' => 1361, 'name' => 'Vidrio, alfarería y cerámica no artesanal']);
        Area::create(['code' => 1371, 'name' => 'Fundición']);
        Area::create(['code' => 1381, 'name' => 'Soldadura y pailería']);
        Area::create(['code' => 1382, 'name' => 'Operación de maquinas  herramienta']);
        Area::create(['code' => 1383, 'name' => 'Diseño industrial y estructural']);
        Area::create(['code' => 1391, 'name' => 'Acabados industriales']);
        Area::create(['code' => 1392, 'name' => 'Relojería y joyería']);
        Area::create(['code' => 1393, 'name' => 'Artesanías y manualidades']);
        Area::create(['code' => 1400, 'name' => 'Construcción en general']);
        Area::create(['code' => 1401, 'name' => 'Albañilería']);
        Area::create(['code' => 1402, 'name' => 'Herrería']);
        Area::create(['code' => 1403, 'name' => 'Azulejería']);
        Area::create(['code' => 1404, 'name' => 'Diseño arquitectónico']);
        Area::create(['code' => 1405, 'name' => 'Plomería y fontanería']);
        Area::create(['code' => 1407, 'name' => 'Pintura']);
        Area::create(['code' => 1408, 'name' => 'Tapicería de paredes']);
        Area::create(['code' => 1409, 'name' => 'Maquinaria para construcción']);
        Area::create(['code' => 1500, 'name' => 'Electricidad general']);
        Area::create(['code' => 1501, 'name' => 'Electromecánica']);
        Area::create(['code' => 1502, 'name' => 'Electrónica']);
        Area::create(['code' => 2000, 'name' => 'Servicios']);
        Area::create(['code' => 2100, 'name' => 'Turismo']);
        Area::create(['code' => 2101, 'name' => 'Hotelería']);
        Area::create(['code' => 2102, 'name' => 'Restaurantes']);
        Area::create(['code' => 2103, 'name' => 'Guía de turistas']);
        Area::create(['code' => 2201, 'name' => 'Conducción de vehículos']);
        Area::create(['code' => 2301, 'name' => 'Almacenista e inventarios']);
        Area::create(['code' => 2501, 'name' => 'Servicios financieros']);
        Area::create(['code' => 2502, 'name' => 'Servicios bancarios']);
        Area::create(['code' => 2503, 'name' => 'Seguros']);
        Area::create(['code' => 2600, 'name' => 'Educación']);
        Area::create(['code' => 2601, 'name' => 'Idiomas']);
        Area::create(['code' => 2602, 'name' => 'Métodos pedagógicos y medios de enseñanza']);
        Area::create(['code' => 2603, 'name' => 'Formación y actualización docente']);
        Area::create(['code' => 2604, 'name' => 'Actualización de programas educativos']);
        Area::create(['code' => 2605, 'name' => 'Materias formativas y tecnológicas']);
        Area::create(['code' => 2700, 'name' => 'Salud']);
        Area::create(['code' => 2701, 'name' => 'Cursos de capacitacion dirigidos a paramédicos y enfermeras']);
        Area::create(['code' => 2703, 'name' => 'Prótesis']);
        Area::create(['code' => 2704, 'name' => 'Terapias']);
        Area::create(['code' => 2706, 'name' => 'Salud animal']);
        Area::create(['code' => 2900, 'name' => 'Servicios de belleza']);
        Area::create(['code' => 3000, 'name' => 'Administración, contabilidad y economía']);
        Area::create(['code' => 3110, 'name' => 'Administración general']);
        Area::create(['code' => 3111, 'name' => 'Administración de empresas agropecuarias, forestales o pesqueras']);
        Area::create(['code' => 3112, 'name' => 'Administración de empresas industriales']);
        Area::create(['code' => 3113, 'name' => 'Administración de empresas comerciales']);
        Area::create(['code' => 3114, 'name' => 'Administración de empresas turísticas']);
        Area::create(['code' => 3115, 'name' => 'Administración de empresas de servicios']);
        Area::create(['code' => 3116, 'name' => 'Administración publica']);
        Area::create(['code' => 3121, 'name' => 'Apoyo a la operación administrativa']);
        Area::create(['code' => 3122, 'name' => 'Auxiliar administrativo']);
        Area::create(['code' => 3123, 'name' => 'Archivo']);
        Area::create(['code' => 3124, 'name' => 'Apoyo secretarial']);
        Area::create(['code' => 3125, 'name' => 'Auxiliar de crédito y cobranza']);
        Area::create(['code' => 3126, 'name' => 'Otros apoyos']);
        Area::create(['code' => 3130, 'name' => 'Formación empresarial y gerencial']);
        Area::create(['code' => 3131, 'name' => 'Apoyo a la calidad']);
        Area::create(['code' => 3132, 'name' => 'Recursos humanos']);
        Area::create(['code' => 3133, 'name' => 'Formación y actualización de instructores']);
        Area::create(['code' => 3134, 'name' => 'Administración de la capacitación y adiestramiento de personal']);
        Area::create(['code' => 3135, 'name' => 'Relaciones laborales']);
        Area::create(['code' => 3136, 'name' => 'Monitoreo y supervisión']);
        Area::create(['code' => 3137, 'name' => 'Productividad y competitividad']);
        Area::create(['code' => 3138, 'name' => 'Dirección y gestión']);
        Area::create(['code' => 3139, 'name' => 'Planeación']);
        Area::create(['code' => 3140, 'name' => 'Jurídico']);
        Area::create(['code' => 3141, 'name' => 'Derecho laboral']);
        Area::create(['code' => 3142, 'name' => 'Derecho mercantil']);
        Area::create(['code' => 3143, 'name' => 'Derecho fiscal']);
        Area::create(['code' => 3144, 'name' => 'Derecho penal']);
        Area::create(['code' => 3145, 'name' => 'Derecho en general']);
        Area::create(['code' => 3146, 'name' => 'Derecho internacional']);
        Area::create(['code' => 3147, 'name' => 'Marcas y patentes']);
        Area::create(['code' => 148, 'name' => 'Peritaje y evaluación']);
        Area::create(['code' => 3200, 'name' => 'Contabilidad general y auditoria']);
        Area::create(['code' => 3201, 'name' => 'Contabilidad de costos']);
        Area::create(['code' => 3202, 'name' => 'Contabilidad fiscal']);
        Area::create(['code' => 3203, 'name' => 'Contabilidad financiera']);
        Area::create(['code' => 3204, 'name' => 'Contabilidad pública']);
        Area::create(['code' => 3205, 'name' => 'Auditoria']);
        Area::create(['code' => 3300, 'name' => 'Economía general']);
        Area::create(['code' => 4000, 'name' => 'Comercialización']);
        Area::create(['code' => 4100, 'name' => 'Mercadotecnia']);
        Area::create(['code' => 4200, 'name' => 'Promoción y publicidad']);
        Area::create(['code' => 4300, 'name' => 'Ventas y distribución']);
        Area::create(['code' => 4400, 'name' => 'Comercio internacional y aduanas']);
        Area::create(['code' => 5000, 'name' => 'Mantenimiento y reparación']);
        Area::create(['code' => 5101, 'name' => 'Mantenimiento y reparación de maquinas y equipo agropecuario y pesca']);
        Area::create(['code' => 5102, 'name' => 'Mantenimiento y reparación de maquinaria y equipo industrial']);
        Area::create(['code' => 5103, 'name' => 'Mantenimiento, reparación y soporte técnico de equipo de cómputo']);
        Area::create(['code' => 5104, 'name' => 'Mantenimiento y reparación de equipo especializado']);
        Area::create(['code' => 5105, 'name' => 'Mantenimiento y reparación de equipo de comunicación']);
        Area::create(['code' => 5201, 'name' => 'Mantenimiento y reparación de automóviles, autobuses y camiones']);
        Area::create(['code' => 5202, 'name' => 'Mantenimiento y reparación de aeronaves']);
        Area::create(['code' => 5203, 'name' => 'Mantenimiento y reparación de transportes marítimos']);
        Area::create(['code' => 5205, 'name' => 'Mantenimiento y reparación de equipo ferroviario']);
        Area::create(['code' => 5300, 'name' => 'Mantenimiento y reparación de electrodomésticos']);
        Area::create(['code' => 5301, 'name' => 'Mantenimiento y reparación de equipos eléctricos']);
        Area::create(['code' => 5400, 'name' => 'Servicios']);
        Area::create(['code' => 5401, 'name' => 'De limpieza industrial y domestica']);
        Area::create(['code' => 5402, 'name' => 'Personales']);
        Area::create(['code' => 5403, 'name' => 'Inmobiliarios']);
        Area::create(['code' => 5404, 'name' => 'Consultorías']);
        Area::create(['code' => 5405, 'name' => 'Ambientales']);
        Area::create(['code' => 5406, 'name' => 'Funerarios']);
        Area::create(['code' => 5407, 'name' => 'Investigación en general']);
        Area::create(['code' => 5500, 'name' => 'Control de plagas en campo, industria y hogares']);
        Area::create(['code' => 6000, 'name' => 'Seguridad']);
        Area::create(['code' => 6100, 'name' => 'Seguridad industrial']);
        Area::create(['code' => 6200, 'name' => 'Seguridad bancaria']);
        Area::create(['code' => 6300, 'name' => 'Seguridad publica']);
        Area::create(['code' => 6400, 'name' => 'Higiene y seguridad en el trabajo']);
        Area::create(['code' => 7000, 'name' => 'Desarrollo personal y familiar']);
        Area::create(['code' => 7100, 'name' => 'Relaciones humanas']);
        Area::create(['code' => 7200, 'name' => 'Actividades culturales y artísticas']);
        Area::create(['code' => 7300, 'name' => 'Actividades deportivas']);
        Area::create(['code' => 7400, 'name' => 'Relaciones familiares']);
        Area::create(['code' => 8000, 'name' => 'Uso de tecnologías de la información y comunicación']);
        Area::create(['code' => 8100, 'name' => 'Programación de computadoras']);
        Area::create(['code' => 8101, 'name' => 'Paquetería de computo']);
        Area::create(['code' => 8102, 'name' => 'Bases de datos']);
        Area::create(['code' => 8103, 'name' => 'Computación en general']);
        Area::create(['code' => 8200, 'name' => 'Correo']);
        Area::create(['code' => 8201, 'name' => 'Mensajería y paquetería especializada']);
        Area::create(['code' => 8202, 'name' => 'Telégrafos']);
        Area::create(['code' => 8203, 'name' => 'Servicio telefónico']);
        Area::create(['code' => 8204, 'name' => 'Radio']);
        Area::create(['code' => 8205, 'name' => 'Televisión']);
        Area::create(['code' => 8206, 'name' => 'Cinematografía']);
        Area::create(['code' => 8207, 'name' => 'Fotografía']);
        Area::create(['code' => 8300, 'name' => 'Telecomunicaciones']);
        Area::create(['code' => 8301, 'name' => 'Técnicas de comunicación']);
        Area::create(['code' => 8302, 'name' => 'Operación de equipos de comunicación en general']);
        Area::create(['code' => 8303, 'name' => 'Productor de recursos para la comunicación']);
        Area::create(['code' => 9000, 'name' => 'Participación social']);
        Area::create(['code' => 9100, 'name' => 'Participación política']);
        Area::create(['code' => 9200, 'name' => 'Organización comunitaria']);
        Area::create(['code' => 9300, 'name' => 'Capacitacion sindical']);
        Area::create(['code' => 9400, 'name' => 'Áreas diversas']);
        Area::create(['code' => 9500, 'name' => 'No especificado']);
    }
}
